# Generated by Django 2.2 on 2019-09-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydetails',
            name='hasterrace',
        ),
        migrations.RemoveField(
            model_name='proprooms',
            name='bednumber',
        ),
    ]
