# Generated by Django 2.2 on 2019-09-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0002_auto_20190912_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='userprofilephoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
