# Generated by Django 2.2 on 2019-09-16 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0003_auto_20190915_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='useremail',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='userid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='userregdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
