# Generated by Django 2.2 on 2019-09-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0007_addressdetails_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='regdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
