# Generated by Django 2.2 on 2019-09-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0008_propertydetails_regdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='propdeposit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
