# Generated by Django 2.2 on 2019-09-17 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0009_propertydetails_propdeposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='address',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='useradmission.AddressDetails'),
        ),
    ]
