# Generated by Django 2.2 on 2019-09-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0011_auto_20190918_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressdetails',
            name='addressid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='propid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='userid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
