# Generated by Django 2.2 on 2019-09-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0012_auto_20190919_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='propsize',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
