# Generated by Django 2.2 on 2019-09-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0013_auto_20190919_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='regdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
