# Generated by Django 2.2 on 2019-09-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0014_auto_20190919_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='hasbalcony',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
