# Generated by Django 2.2 on 2019-09-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0015_auto_20190919_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='picurl1',
            field=models.ImageField(blank=True, null=True, upload_to=b'propertyimages'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='picurl2',
            field=models.ImageField(blank=True, null=True, upload_to=b'propertyimages'),
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='picurl3',
            field=models.ImageField(blank=True, null=True, upload_to=b'propertyimages'),
        ),
    ]
