# Generated by Django 2.2 on 2019-09-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0017_auto_20190921_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='userregdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
