# Generated by Django 2.2 on 2019-09-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0019_auto_20190921_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='verifystatus',
            field=models.CharField(default='unverified', max_length=15),
        ),
    ]
