# Generated by Django 2.2 on 2019-09-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0020_propertydetails_verifystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='washroomstyle',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
