# Generated by Django 2.2 on 2019-09-23 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0021_auto_20190923_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='landlord',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='useradmission.UserDetails'),
        ),
    ]
