# Generated by Django 2.2 on 2019-09-26 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0022_propertydetails_landlord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='landlord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='useradmission.UserDetails'),
        ),
    ]
