# Generated by Django 2.2 on 2019-09-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0023_auto_20190927_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='userprofilephoto',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
