# Generated by Django 2.2 on 2019-09-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0024_auto_20190927_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydetails',
            name='propavailablebeds',
        ),
        migrations.RemoveField(
            model_name='propertydetails',
            name='propavailablerooms',
        ),
        migrations.RemoveField(
            model_name='propertydetails',
            name='propcapacitybeds',
        ),
        migrations.AlterField(
            model_name='proprooms',
            name='ismasterroom',
            field=models.BooleanField(default=False),
        ),
    ]
