# Generated by Django 2.2 on 2019-09-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0025_auto_20190929_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydetails',
            name='propcapacityrooms',
        ),
    ]
