# Generated by Django 2.2 on 2019-09-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0027_propertydetails_propcapacityrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='propavailablebeds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='propavailablerooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='propcapacitybeds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
