# Generated by Django 2.2 on 2019-09-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0028_auto_20190929_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprooms',
            name='bedavailable',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
