# Generated by Django 2.2 on 2019-10-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0030_auto_20191001_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='availabilitystatus',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
