# Generated by Django 2.2 on 2019-10-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0031_auto_20191001_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='verifystatus',
            field=models.BooleanField(default=0, max_length=15),
        ),
    ]
