# Generated by Django 2.2 on 2019-10-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0032_auto_20191002_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidrecords',
            old_name='bidamount',
            new_name='rentbid',
        ),
    ]
