# Generated by Django 2.2 on 2019-10-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0034_bidrecords_depositbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidrecords',
            name='bedbid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bidrecords',
            name='biddescription',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bidrecords',
            name='personcatbid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bidrecords',
            name='rentingcatbid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bidrecords',
            name='staybid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bidrecords',
            name='biddate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bidrecords',
            name='bidtime',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
