# Generated by Django 2.2 on 2019-10-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0036_auto_20191019_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprooms',
            name='roomtag',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
