# Generated by Django 2.2 on 2019-10-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0038_auto_20191019_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='bookingid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
