# Generated by Django 2.2 on 2019-10-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0041_auto_20191020_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='token',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
