# Generated by Django 2.2 on 2019-10-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0042_userdetails_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyrented',
            old_name='rentduedate',
            new_name='enddate',
        ),
    ]
