# Generated by Django 2.2 on 2019-10-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0043_auto_20191020_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentreceipt',
            name='dateofpayment',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentreceipt',
            name='monthfine',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
