# Generated by Django 2.2 on 2019-10-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0044_auto_20191021_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentreceipt',
            name='methodofpayment',
            field=models.CharField(blank=True, default='token', max_length=10, null=True),
        ),
    ]
