# Generated by Django 2.2 on 2019-10-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0045_auto_20191021_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentreceipt',
            name='status',
        ),
    ]
