# Generated by Django 2.2 on 2019-10-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0046_remove_rentreceipt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyrented',
            name='enddate',
        ),
        migrations.AddField(
            model_name='propertyrented',
            name='staymonthcount',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
    ]
