# Generated by Django 2.2 on 2019-10-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0048_rentreceipt_amountpaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='availabilitystatus',
            field=models.BooleanField(default=False, max_length=15),
        ),
    ]
