# Generated by Django 2.2 on 2019-10-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmission', '0049_auto_20191022_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='messageofverify',
            field=models.TextField(blank=True, default='Hello', null=True),
        ),
    ]
