# Generated by Django 2.2 on 2019-09-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20190917_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressdetails',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
