# Generated by Django 2.2 on 2019-09-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_addressdetails_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressdetails',
            name='pincode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
