# Generated by Django 2.2 on 2019-09-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20190917_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctioninfo',
            name='prop',
        ),
        migrations.RemoveField(
            model_name='bidrecords',
            name='auc',
        ),
        migrations.RemoveField(
            model_name='bidrecords',
            name='user',
        ),
        migrations.RemoveField(
            model_name='propertydetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='propertydetails',
            name='amenity',
        ),
        migrations.RemoveField(
            model_name='propertyrented',
            name='prop',
        ),
        migrations.RemoveField(
            model_name='propertyrented',
            name='user',
        ),
        migrations.RemoveField(
            model_name='proprooms',
            name='prop',
        ),
        migrations.RemoveField(
            model_name='rentreceipt',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='searchrecords',
            name='prop',
        ),
        migrations.RemoveField(
            model_name='searchrecords',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='prop',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercontactnumber',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='address',
        ),
        migrations.DeleteModel(
            name='AddressDetails',
        ),
        migrations.DeleteModel(
            name='AuctionInfo',
        ),
        migrations.DeleteModel(
            name='BidRecords',
        ),
        migrations.DeleteModel(
            name='PropertyAmenities',
        ),
        migrations.DeleteModel(
            name='PropertyDetails',
        ),
        migrations.DeleteModel(
            name='PropertyRented',
        ),
        migrations.DeleteModel(
            name='PropRooms',
        ),
        migrations.DeleteModel(
            name='RentReceipt',
        ),
        migrations.DeleteModel(
            name='SearchRecords',
        ),
        migrations.DeleteModel(
            name='TourBooking',
        ),
        migrations.DeleteModel(
            name='UserContactNumber',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
